    import { StyleSheet, Dimensions, Platform } from "react-native";

    const { width: SCREEN_WIDTH } = Dimensions.get("window");

    export const styles = StyleSheet.create({
        container: {
        flex: 1,
        backgroundColor: "#121214", 
        padding: 12,
        paddingTop: 50,
    },
    title: {
        color: "#00ffff",
        fontSize: 24,
        fontWeight: "bold",
        marginBottom: 15,
        textAlign: "center",
    },
    sectionTitle: {
        color: "#fff",
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 10,
    },
    pickerContainer: {
        marginBottom: 25,
    },
    mainPickerStyle: {
        height: 40,
        fontSize: 15,
    },
    fallbackPicker: {
        backgroundColor: '#222',
        paddingVertical: 5,
        paddingHorizontal: 2,
        borderRadius: 5,
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#444',
        width: "100%",
        height: 28,
    },
    playerCommandsBtn: {
        backgroundColor: "#1e3a8a",
        borderColor: "#3b82f6",
        borderWidth: 1,
        borderRadius: 6,
        paddingVertical: 6,
        paddingHorizontal: 12,
        marginTop: 10,
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
    },
    playerCommandsText: {
        color: "#fff",
        fontSize: 11,
        fontWeight: "bold",
        textTransform: "uppercase",
        letterSpacing: 0.5,
    },
    horizontalScroll: {
        marginHorizontal: -12, // Compensa o padding do container para encostar nas bordas
        paddingHorizontal: 12,
        marginBottom: 10,
    },
    pageContainer: {
        width: Platform.OS === 'web' ? SCREEN_WIDTH * 0.45 : SCREEN_WIDTH - 24, // Ajuste fluido web/mobile
        marginLeft: 0,
        marginRight: Platform.OS === 'web' ? 10 : 24, // Dá o espaço necessário na direita para não cortar no mobile
    },
    pageIndicatorText: {
        color: "#3b82f6",
        fontSize: 11,
        fontWeight: "900",
        letterSpacing: 1,
        marginBottom: 8,
        textAlign: "center",
        backgroundColor: "#1c1c1e",
        paddingVertical: 3,
        borderRadius: 4,
    },
    slotsRow: {
        flexDirection: "row",
        justifyContent: "space-between",
    },
    verticalLineDivider: {
        width: 4,
        backgroundColor: "#2a3a5a",
        marginHorizontal: 15,
        borderRadius: 2,
        height: "92%",
        alignSelf: "flex-end",
        borderStyle: "dashed",
    },
    slotCard: {
        flex: 1,
        minHeight: 330, 
        marginHorizontal: 3,
        padding: 6,
        borderRadius: 8,
        borderWidth: 2,
        flexDirection: "column",
        justifyContent: "space-between",
    },
    slotFilled: {
        backgroundColor: "#1a2438",
        borderColor: "#3b82f6",
    },
    slotBacklineFilled: {
        backgroundColor: "#25183a", // Cor roxa discreta para diferenciar o Backline
        borderColor: "#a855f7",
    },
    slotEmpty: {
        backgroundColor: "#1c1c1e",
        borderColor: "#444",
        borderStyle: "dashed",
    },
    topSection: {
        width: "100%",
        marginBottom: 8,
    },
    middleSection: {
        width: "100%",
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center", 
        marginBottom: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#2a3a5a",
        paddingBottom: 8,
    },
    skillsSection: {
        width: "100%",
        flexDirection: "column",
        gap: 12, 
        marginBottom: 8,
    },
    ceSection: {
        width: "100%",
        marginVertical: 4,
    },
    miniDivider: {
        height: 1,
        backgroundColor: "#2a3a5a",
        marginVertical: 6, 
    },
    skillRow: {
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "center", 
        paddingVertical: 2, 
    },
    shortLabelText: {
        color: "#e2e8f0",
        fontSize: 12,
        fontWeight: "bold",
        marginRight: 6, 
    },
    miniPickerWrapper: {
        width: 36,          
    },
    miniPickerStyle: {
        height: 28,
        fontSize: 11,
    },
    bottomSection: {
        width: "100%",
        alignItems: "center",
        borderTopWidth: 1,
        borderTopColor: "#2a3a5a",
        paddingTop: 6,
        marginTop: "auto",
    },
    statsText: {
        color: "#93c5fd",
        fontSize: 11,
        marginVertical: 1,
    },
    placeholderText: {
        color: "#444",
        fontSize: 14,
        textAlign: "center",
        width: "100%",
        marginVertical: 5,
    },
    divider: {
        height: 1,
        backgroundColor: "#2a2a30",
        marginVertical: 25,
    },
    blockedNodeBox: {
        padding: 30,
        backgroundColor: "#221314",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#ef4444",
        alignItems: "center",
    },
    blockedText: {
        color: "#ef4444",
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 6,
    },
    blockedSubText: {
        color: "#fca5a5",
        fontSize: 13,
        textAlign: "center",
    },
    nodePreviewContainer: {
        backgroundColor: "#1a1a1e",
        padding: 12,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#2a2a30",
    },
    nodePreviewTitle: {
        color: "#aaa",
        fontSize: 14,
        marginBottom: 12,
        fontWeight: "500",
    },
    waveRow: {
        flexDirection: "column",   
        paddingVertical: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#222",
    },
    waveLabel: {
        color: "#e2e8f0",
        fontSize: 14,
        fontWeight: "bold",
        textAlign: "center",       
        marginBottom: 10,         
    },
    waveContentContainer: {
        flexDirection: "row",
        alignItems: "center",
        width: "100%",
    },
    enemyNamesList: {
        flexDirection: "row",
        flexWrap: "wrap", 
        flex: 1,
        justifyContent: "flex-start",
        gap: 8,
    },
    fieldBox: {
        width: 70,
        backgroundColor: "#1c1917",
        borderColor: "#78716c",
        borderWidth: 1,
        borderRadius: 6,
        padding: 4,
        minHeight: 65,
        justifyContent: "flex-start",
        alignItems: "center",
    },
    fieldBoxTitle: {
        color: "#a8a29e",
        fontSize: 10,
        fontWeight: "bold",
        textTransform: "uppercase",
        borderBottomWidth: 1,
        borderBottomColor: "#444",
        width: "100%",
        textAlign: "center",
        marginBottom: 4,
    },
    fieldText: {
        color: "#d6d3d1",
        fontSize: 10,
        textAlign: "center",
    },
    // Container que empurra e centraliza os inimigos no espaço restante
    enemiesCentralizedContainer: {
        flex: 1,
        alignItems: "center",
        justifyContent: "center",
    },
    enemyCardBlock: {
        alignItems: "center",
        flexDirection: "column",
    },
    enemyNameTag: {
        color: "#ffaa00", 
        backgroundColor: "#26262b",
        paddingVertical: 4,
        paddingHorizontal: 10,
        borderRadius: 4,
        fontSize: 13,
        borderWidth: 1,
        borderColor: "#3a3a40",
        textAlign: "center",
    },
    // Estilo do texto de HP abaixo do nome
    enemyHpText: {
        color: "#ef4444",
        fontSize: 11,
        fontWeight: "600",
        marginTop: 3,
    },
    emptyNodeBox: {
        padding: 30,
        backgroundColor: "#141416",
        borderRadius: 8,
        borderWidth: 1,
        borderColor: "#222",
        borderStyle: "dashed",
    }
    });

    export const modalStyles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.75)', 
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        width: '85%',
        backgroundColor: '#1c1c1e', 
        borderRadius: 12,
        padding: 16,
        borderWidth: 1,
        borderColor: '#2c2c2e',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.4,
        shadowRadius: 6,
        elevation: 10,
    },
    modalTitle: {
        color: '#00ffff', 
        fontSize: 16,
        fontWeight: 'bold',
        marginBottom: 12,
        textAlign: 'center',
        borderBottomWidth: 1,
        borderBottomColor: '#2c2c2e',
        paddingBottom: 10,
    },
    optionButton: {
        paddingVertical: 14,
        paddingHorizontal: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#2c2c2e',
        width: '100%',
    },
    optionSelected: {
        backgroundColor: '#1a2438', 
    },
    optionText: {
        color: '#e2e8f0', 
        fontSize: 15,
        textAlign: 'left',
    },
    optionTextSelected: {
        color: '#3b82f6', 
        fontWeight: 'bold',
    },
    });