export type Traits = 
'Male' | 'Female' | 'FeminineLooking' 
| 'Lawful' | 'Neutral' | 'Chaotic' | 'Good' | 'Balanced' | 'Evil' | 'Insane' | 'Summer'
| 'Amazoness' | 'AnimalCharacteristics' | 'ArgoRelated' | 'Arthur' | 'ArtificialDemon' | 'ArtoriaCaster' | 'ArtoriaFace' | 'Automata' 
| 'BeautifulBoy' | 'Bunny' 
| 'Caenis' | 'Child' | 'ConsortYu' | 'CostumeOwning' 
| 'Defender' | 'DemiServant' | 'Demon' | 'DemonBeast' | 'DemonGodPillar' | 'Demonic' | 'DemonicBeast' | 'Divinity' | 'Dragon' | 'DragonSlayer' 
| 'ExistenceOutsidetheDomain' 
| 'Fae' | 'FairyTale' | 'FateStayNight' 
| 'Genji' | 'Ghost' | 'Giant' | 'Goddess' | 'GreekMythologyMale' | 'Group' 
| 'Hominidae' | 'Human' | 'Humanoid' 
| 'Illya' | 'ImmunetoPigify' 
| 'King' 
| 'Levitating' | 'LivingHuman' | 'LovedOne' 
| 'Mechanical' | 'Moon' | 'MountLiang' 
| 'Nobunaga' | 'Non-Animal' | 'NonHominidae' 
| 'ObstacleMaker' | 'Oni' 
| 'PseudoServant' 
| 'Riding' | 'Roman' | 'RoundTableKnight' 
| 'Saber' | 'SakuraSeries' | 'Serpent' | 'Servant' | 'SevenClasses' | 'ShadowServant' | 'Shinsengumi' | 'ShutenDoji' | 'Skeleton' | 'Soldier' | 'SummerMode' | 'SuperLarge' 
| 'ThreattoHumanity' 
| 'Undead' 
| 'Valkyrie' 
| 'WeakEnumaElish' | 'Werebeast' | 'WildBeast' 
| 'Zombie' 
| '3StarorLower';